version: 2
updates:
  # Check for updates to GitHub Actions every week
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
